### ISSUE TITLE
Representar en los diagramas UML los atributos y los paquetes

### ISSUE THREAD

**Issue by javilb26** [javilg/P3-VVS#15]
En el diagrama UML faltan los atributos. Además, al haber varios paquetes debería haber varios diagramas UML.

**Comment by lauramcastro** [comment]
Ok, pero neste caso, como o proxecto é pequeno, non fagades varios diagramas (por paquete), facede só un. O que dicides (1 paquete = 1 diagrama, + 1 diagrama xeral sen detalle de atributos/métoso) sería o correcto, simplemente neste caso indícovos que non é preciso porque os diagramas son pequenos e podemos poñer todo o nivel de detalle de cada paquete nun único diagrama manexable.
